version: '3.8'
services:
    keycloak:
        build:
           context: keycloak
           dockerfile: Dockerfile
        depends_on:
            - postgres
        ports:
           - "8095:8080"
        restart: on-failure
        command: start-dev --import-realm --proxy-headers xforwarded
    azurite:
        build:
           context: azurite
           dockerfile: Dockerfile
        ports:
          - "10000:10000"
          - "10001:10001"
          - "10002:10002"
        restart: on-failure	  
    postgres:
        image: "maurodatamapper/postgres:12.14-alpine"
        build: ./postgres
        shm_size: 512mb
        environment:
            POSTGRES_PASSWORD: postgresisawesome
        volumes:
            - postgres12:/var/lib/postgresql/data
        restart: on-failure
    sde-admin-api:
        env_file: .env
        build:
           context: sde-admin-api
           dockerfile: Dockerfile
        ports:
         - "8093:8081"
        depends_on:
            - postgres
            - keycloak
            - azurite
        restart: on-failure
    sde-researcher-api:
        env_file: .env
        build:
           context: sde-researcher-api
           dockerfile: Dockerfile
        ports:
         - "8094:8082"
        depends_on:
            - postgres
            - keycloak
            - azurite
        restart: on-failure
    mauro-data-mapper:
        image: "maurodatamapper/mauro-data-mapper:${MDM_TAG}"
        build:
            context: mauro-data-mapper
            args:
                MDM_APPLICATION_COMMIT: "${MDM_APPLICATION_COMMIT}"
                MDM_UI_COMMIT: "develop"
                ADDITIONAL_PLUGINS: "uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-authentication-openid-connect:2.3.0-SNAPSHOT;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-explorer:1.0.0-SNAPSHOT"
                MDM_UI_THEME_NAME: "default"
                CACHE_BURST: "${CACHE_BURST}"
                MDM_EXPLORER_API_ENDPOINT: "http://localhost:8082/api"
                SDE_RESEARCHER_API_ENDPOINT: "http://localhost:8094/"
        environment:
            PGPASSWORD: postgresisawesome
            runtime.config.path: /usr/local/tomcat/conf/runtime.yml
        ports:
            - "8082:8080"
        depends_on:
            - postgres
        volumes:
            - lucene_index:/lucene
            - ./shared_volumes/logs/maurodatamapper:/usr/local/tomcat/logs
            - ./shared_volumes/tmp:/tmp
            - ./mauro-data-mapper/config/runtime.yml:/usr/local/tomcat/conf/runtime.yml
            - ./mauro-data-mapper/prebuilt-explorer:/prebuilt-explorer
            - ./mauro-data-mapper/prebuilt-sde-admin:/prebuilt-sde-admin
            - ./mauro-data-mapper/libs:/libs
        restart: on-failure

# Persistence capability to systems,
# Any volumes labelled below will ensure persistence when containers removed unless the volume is removed as well
volumes:
    postgres12:
        driver: local
    lucene_index:
        driver: local

