version: '3.8'
services:
    keycloak:
        env_file: .env
        build:
           context: keycloak
           dockerfile: Dockerfile
        depends_on:
            - postgres
        ports:
           - "8095:8080"
        environment:
            - KC_HOSTNAME
            - KC_HOSTNAME_PORT
        restart: always
        command: start-dev --import-realm --proxy-headers xforwarded
    azurite:
        build:
           context: azurite
           dockerfile: Dockerfile
        ports:
          - "10000:10000"
          - "10001:10001"
          - "10002:10002"
        restart: always
    postgres:
        build: ./postgres
        shm_size: 512mb
        environment:
            POSTGRES_PASSWORD: postgresisawesome
        volumes:
            - postgres12:/var/lib/postgresql/data
        restart: always
    sde-core:
        env_file: .env
        build:
            context: sde-core
            dockerfile: Dockerfile
            args:
                - SDE_CORE_GITHUB_PAT=${SDE_CORE_GITHUB_PAT}
                - SDE_CORE_COMMIT=${SDE_CORE_COMMIT:-develop}
        ports:
            - "8081:8081"
            - "8082:8082"
        depends_on:
            - postgres
            - keycloak
            - azurite
        # restart: always
    mauro-data-mapper:
        env_file: .env
        build:
            context: mauro-data-mapper
            args:
                MDM_APPLICATION_COMMIT: "${MDM_APPLICATION_COMMIT}"
                MDM_UI_COMMIT: 'develop'
                ADDITIONAL_PLUGINS: "uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-authentication-openid-connect:2.3.0-SNAPSHOT;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-explorer:1.0.0-OUH-TEST"
                MDM_UI_THEME_NAME: "default"
                CACHE_BURST: "${CACHE_BURST}"
                SDE_ADMIN_API_ENDPOINT: ${SDE_ADMIN_API_ENDPOINT:-http://localhost:8081/}
                MDM_EXPLORER_API_ENDPOINT: ${MDM_EXPLORER_API_ENDPOINT:-http://localhost:8080/api}
                SDE_RESEARCHER_API_ENDPOINT: ${SDE_RESEARCHER_API_ENDPOINT:-http://localhost:8082/}
        environment:
            - PGPASSWORD=postgresisawesome
            - runtime.config.path=/usr/local/tomcat/conf/runtime.yml
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        volumes:
            - lucene_index:/lucene
            - ./shared_volumes/logs/maurodatamapper:/usr/local/tomcat/logs
            - ./shared_volumes/tmp:/tmp
            - ./mauro-data-mapper/config/runtime.yml:/usr/local/tomcat/conf/runtime.yml
            - ./mauro-data-mapper/prebuilt-explorer:/prebuilt-explorer
            - ./mauro-data-mapper/prebuilt-sde-admin:/prebuilt-sde-admin
            - ./mauro-data-mapper/libs:/libs
        # restart: always

# Persistence capability to systems,
# Any volumes labelled below will ensure persistence when containers removed unless the volume is removed as well
volumes:
    postgres12:
        driver: local
    lucene_index:
        driver: local

