micronaut:
  application:
    name: sdeManagementApisResearcher
  server:
    port: 8082
    cors:
      enabled: true
    max-request-size: '50MB'
    multipart:
      max-file-size: '50MB'
  security:
    authentication: cookie
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_TOKEN_SIGNATURE_GENERATOR_SECRET}
              jws-algorithm: HS256
        encryptions:
          secret:
            generator:
              secret: ${JWT_TOKEN_ENCRYPTION_GENERATOR_SECRET}
              jwe-algorithm: A256KW
              encryption-method: A128CBC-HS256
    oauth2:
      clients:
#        microsoft-azure:
#          enabled: ${OAUTH_MS_AZURE_ENABLED:true}
#          client-id: ${OAUTH_MS_AZURE_CLIENT_ID:''}
#          client-secret: ${OAUTH_MS_AZURE_CLIENT_SECRET:''}
#          openid:
#            issuer: ${OAUTH_MS_AZURE_ISSUER_URL:''}
        keycloak:
          enabled: true
          client-id: mdm
          client-secret: 4b3b7290-7629-4b88-b310-df256adc8fed
          openid:
            issuer: http://keycloak:8080/realms/test/
    redirect:
      login-success: http://localhost:8082/explorer/#/sde/auth/finalize/sign-in-success
      login-failure: http://localhost:8082/explorer/#/sde/auth/finalize/sign-in-failed
      logout: http://localhost:8082/explorer/#/sde/auth/finalize/sign-out
netty:
  default:
    allocator:
      max-order: 3
jackson:
  serialization:
    writeDatesAsTimestamps: false
#For debugging:
#logger:
#  levels:
#    io.netty: DEBUG
#    io.micronaut: DEBUG