micronaut:
  application:
    name: sdeManagementApisResearcher
  server:
    port: 8082
    cors:
      enabled: true
    configurations:
      ui:
        allowed-origins:
          - ${RESEARCHER_CORS_ORIGIN}
    max-request-size: '50MB'
    multipart:
      max-file-size: '50MB'
  security:
    authentication: cookie
    token:
      jwt:
        cookie:
          cookie-max-age: 12h
        signatures:
          secret:
            generator:
              secret: ${JWT_TOKEN_SIGNATURE_GENERATOR_SECRET}
              jws-algorithm: HS256
        encryptions:
          secret:
            generator:
              secret: ${JWT_TOKEN_ENCRYPTION_GENERATOR_SECRET}
              jwe-algorithm: A256KW
              encryption-method: A128CBC-HS256
        generator:
          access-token:
            expiration: 28800
    oauth2:
      callback-uri: ${OAUTH_RESEARCHER_CALLBACK_URI}
      clients:
        microsoft-azure:
          enabled: ${OAUTH_RESEARCHER_MS_AZURE_ENABLED}
          client-id: ${OAUTH_RESEARCHER_MS_AZURE_CLIENT_ID}
          client-secret: ${OAUTH_RESEARCHER_MS_AZURE_CLIENT_SECRET}
          openid:
            issuer: ${OAUTH_RESEARCHER_MS_AZURE_ISSUER_URL}
        keycloak:
          enabled: false
          client-id: mdm
          client-secret: 4b3b7290-7629-4b88-b310-df256adc8fed
          openid:
            issuer: http://keycloak:8080/realms/test/
    redirect:
      login-success: ${RESEARCHER_LOGIN_SUCCESS_URI}
      login-failure: ${RESEARCHER_LOGIN_FAILURE_URI}
      logout: ${RESEARCHER_LOGOUT_URI}
netty:
  default:
    allocator:
      max-order: 3
jackson:
  serialization:
    writeDatesAsTimestamps: false
#For debugging:
#logger:
#  levels:
#    io.netty: DEBUG
#    io.micronaut: DEBUG
