---
# Database connection details
---
database:
    host: postgres
    port: 5432
    name: maurodatamapper
dataSource:
    username: maurodatamapperuser
    password: jF80LQyP4BbH
---
# MDM configuration properties
---
maurodatamapper:
    authority:
        name: 'Mauro Data Mapper'
        url: http://localhost
---
# Standard Email configuration
---
simplejavamail:
    smtp:
        username: ''
        password: ''
        host: ''
        port: ''
    transportstrategy: SMTP_TLS
---
# mdm-plugin-email-proxy Configuration
---
#emailServiceUrl: ''
#emailServiceUsername: ''
#emailServicePassword: ''
---
# CORS
# See http://docs.grails.org/latest/guide/theWebLayer.html#cors
---
grails:
    cors:
        enabled: true
        # The following are the defaults
        # allowedOrigins: [] # Cannot use allowedOrigins with *, they have to be clearly stated origins
        allowedOriginPatterns: [ '*' ]
        allowedMethods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'HEAD' ]
        allowedHeaders: [ 'origin', 'content-type', 'accept', 'authorization', 'pragma', 'cache-control' ]
        #exposedHeaders: null
        #maxAge: 1800
        #allowCredentials: true
    assets:
        mapping: 'api_assets'
    databinding:
        dateFormats:
            - "yyyy-MM-dd'T'HH:mm:ss.SSSSSSXXX"
            - "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
            - "yyyy-MM-dd'T'HH:mm:ss.SSXXX"
            - "yyyy-MM-dd'T'HH:mm:ss.SXXX"
            - "yyyy-MM-dd'T'HH:mm:ssXXX"
            - 'yyyy-MM-dd HH:mm:ss.S'
            - "yyyy-MM-dd'T'HH:mm:ss'Z'"
            - "yyyy-MM-dd HH:mm:ss.S z"
            - "yyyy-MM-dd"

hibernate:
    search:
        backend:
            directory:
                root: '/lucene'
